// PDF/A's /OutputIntents requires an embedded ICC profile stream. Built
// programmatically (ICC v2.1 display profile, D50 PCS, the standard
// Bradford-adapted sRGB primaries) rather than shipped as an opaque binary
// asset, so the whole thing stays reviewable as code. Verified structurally
// (every tag's declared offset+size stays in bounds, matches its own type
// signature) AND against two independent real-world readers before this
// was written: `file` (libmagic) correctly identifies it as a "color
// profile 2.1, RGB/XYZ-mntr device"; macOS's `sips --setProperty profile`
// accepted it and re-reports the embedded description string when read
// back from a PNG it was attached to.
//
// The TRC (tone response curve) is a single pure gamma-2.2 curve, not the
// exact piecewise sRGB transfer function — a standard, widely-used
// simplification (the same one many "sRGB-compatible" profiles ship) —
// the goal here is a structurally valid, genuinely usable ICC profile for
// PDF/A conformance, not colorimetric perfection.

function be32(v: number): Uint8Array {
  const b = new Uint8Array(4)
  new DataView(b.buffer).setUint32(0, v >>> 0, false)
  return b
}
function be16(v: number): Uint8Array {
  const b = new Uint8Array(2)
  new DataView(b.buffer).setUint16(0, v & 0xffff, false)
  return b
}
function s15Fixed16(v: number): Uint8Array {
  const b = new Uint8Array(4)
  new DataView(b.buffer).setInt32(0, Math.round(v * 65536), false)
  return b
}
function tag4(s: string): Uint8Array {
  return new TextEncoder().encode(s)
}
function concat(...parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((n, p) => n + p.length, 0)
  const out = new Uint8Array(total)
  let off = 0
  for (const p of parts) { out.set(p, off); off += p.length }
  return out
}
function pad4(buf: Uint8Array): Uint8Array {
  const rem = buf.length % 4
  return rem === 0 ? buf : concat(buf, new Uint8Array(4 - rem))
}

function descType(ascii: string): Uint8Array {
  const asciiBuf = concat(tag4(ascii), new Uint8Array([0]))
  return pad4(concat(
    tag4('desc'), be32(0),
    be32(asciiBuf.length), asciiBuf,
    be32(0), be32(0),           // unicode language code, unicode count
    be16(0), new Uint8Array([0]), // scriptcode code, scriptcode count
    new Uint8Array(67),          // 67-byte macintosh field
  ))
}
function textType(ascii: string): Uint8Array {
  const asciiBuf = concat(tag4(ascii), new Uint8Array([0]))
  return pad4(concat(tag4('text'), be32(0), asciiBuf))
}
function xyzType(x: number, y: number, z: number): Uint8Array {
  return pad4(concat(tag4('XYZ '), be32(0), s15Fixed16(x), s15Fixed16(y), s15Fixed16(z)))
}
function curvType(gamma: number): Uint8Array {
  return pad4(concat(tag4('curv'), be32(0), be32(1), be16(Math.round(gamma * 256))))
}

let cached: Uint8Array | null = null

// D50-adapted sRGB primaries/whitepoint (the standard, widely-published
// values used by essentially every real sRGB ICC profile — ICC's PCS is
// always D50, regardless of sRGB's own native D65 whitepoint, so a
// colorimetrically real sRGB profile Bradford-adapts to D50 for these
// exact fields).
export function buildSRGBProfile(): Uint8Array {
  if (cached) return cached

  const tags: [string, Uint8Array][] = [
    ['cprt', textType('Public Domain, generated by daepdf (approximate sRGB, single-gamma TRC)')],
    ['desc', descType('daepdf approximate sRGB')],
    ['wtpt', xyzType(0.9642, 1.0000, 0.8249)],
    ['rXYZ', xyzType(0.4360, 0.2225, 0.0139)],
    ['gXYZ', xyzType(0.3851, 0.7169, 0.0971)],
    ['bXYZ', xyzType(0.1431, 0.0606, 0.7139)],
    ['rTRC', curvType(2.2)],
    ['gTRC', curvType(2.2)],
    ['bTRC', curvType(2.2)],
  ]

  const headerSize = 128
  const tagTableSize = 4 + tags.length * 12
  let offset = headerSize + tagTableSize

  const tagTableEntries: Uint8Array[] = []
  const tagDataParts: Uint8Array[] = []
  for (const [sig, data] of tags) {
    tagTableEntries.push(concat(tag4(sig), be32(offset), be32(data.length)))
    tagDataParts.push(data)
    offset += data.length
  }
  const totalSize = offset

  const header = new Uint8Array(128)
  const hv = new DataView(header.buffer)
  hv.setUint32(0, totalSize, false)     // profile size
  hv.setUint32(8, 0x02100000, false)    // version 2.1.0
  header.set(tag4('mntr'), 12)          // device class: monitor/display
  header.set(tag4('RGB '), 16)          // data color space
  header.set(tag4('XYZ '), 20)          // profile connection space
  header.set(tag4('acsp'), 36)          // file signature
  hv.setUint32(64, 0, false)            // rendering intent: perceptual
  header.set(s15Fixed16(0.9642), 68)    // PCS illuminant (always D50)
  header.set(s15Fixed16(1.0000), 72)
  header.set(s15Fixed16(0.8249), 76)

  const profile = concat(header, be32(tags.length), concat(...tagTableEntries), concat(...tagDataParts))
  cached = profile
  return profile
}
